-- ============================================================
-- CE FICHIER EST OBSOLÈTE — NE PAS UTILISER !
-- Pour reconstruire La Poste, utiliser le script recommandé :
-- scripts/manual-laposte-rebuild.sql
-- ============================================================
